"""08 - Static Export

Builds a report with charts and tables, then exports it as a
self-contained HTML file. No server is started -- just run the
script and open the generated file in a browser.

Run: python examples/08_static_export.py
     -> creates examples/report.html
"""

import os
import webwrench as ww

ww.title("Quarterly Report - Q4 2025")
ww.text("This report was generated by webwrench and exported as a static HTML file.")

ww.divider()

ww.heading("Revenue Summary", level=2)
ww.metric("Total Revenue", "$3.1M", delta="+18% YoY", delta_color="green")

ww.heading("Monthly Breakdown", level=3)
ww.chart(
    [720, 810, 780, 920, 870, 1010],
    type="bar",
    labels=["Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    title="Monthly Revenue ($k)",
)

ww.heading("Regional Performance", level=3)
ww.chart(
    [1200, 950, 620, 330],
    type="pie",
    labels=["North America", "Europe", "Asia-Pacific", "Other"],
    title="Revenue by Region",
)

ww.heading("Top Products", level=3)
ww.table([
    {"Product": "Enterprise Suite", "Revenue": "$1.4M", "Units": "320", "Growth": "+24%"},
    {"Product": "Developer Tools", "Revenue": "$890k", "Units": "1,240", "Growth": "+31%"},
    {"Product": "Analytics Platform", "Revenue": "$540k", "Units": "180", "Growth": "+12%"},
    {"Product": "Cloud Storage", "Revenue": "$270k", "Units": "2,100", "Growth": "+8%"},
], sortable=True)

ww.divider()
ww.text("Report generated with webwrench v0.1.0")

# Export to file
output_path = os.path.join(os.path.dirname(__file__), "report.html")
ww.export(output_path, title="Q4 2025 Quarterly Report")
print(f"Report exported to {output_path}")
